baseurl: "https://cosmic-griffin-43edf2.netlify.app"
languageCode: en-us
title: syaban.site
theme: PaperMod
publishDir: public
googleAnalytics: UA-149424518-1
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
paginate: 5
Taxonomies:
  tag: tags
  category: categories
  series: series
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  mainSections:
    - post
  author: Rizki Syaban
  title: syaban.site
  keyword:
    - Blogs
    - Gists
  images:
    - "https://s.gravatar.com/avatar/d259662d25529f61c2aa84efdd3714ca?s=80"
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false
  ShowFullTextinRSS: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  copyright: syaban
  since: "2023"
  highlightjs: true
  highlightjsstyle: github
  UtterancesRepo: syabana2/hugo-blog
  UtterancesIssueTerm: title
  UtterancesTheme: github-light
  toc: tocbot
  social:
    gravatar: atashish171@gmail.com
    twitter: _ashish_tiwari
    github: syabana2
    linkedin: ashish-tiwari-a40a012b
  assets:
    favicon: favicon.png
    favicon16x16: favicon.png
    favicon32x32: favicon.png
    apple_touch_icon: favicon.png
    safari_pinned_tab: favicon.png
  label:
    text: Rizki Syaban
    iconHeight: 35
  profileMode:
    enabled: false
    imageUrl: "https://www.gravatar.com/avatar/dcb52889deff3e5017a18de40c57add8?s=200"
  homeInfoParams:
    Title: "Welcome Folks!"
    Content: >
      Hi, I’m Syaban, I hope you can find something interesting in my personal blog.

  cover:
    linkFullImages: false
    hiddenInList: false
    hiddenInSingle: false
    responsiveImages: true
  editPost:
    URL: "https://github.com/syabana2/hugo-blog/tree/main/content"
    Text: Suggest Changes
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
  socialIcons:
    - name: github
      url: "https://github.com/syabana2"
    - name: linkedin
      url: "https://www.linkedin.com/in/rizki-sya-ban-aryanto-889a19147/"
    - name: instagram
      url: "https://www.instagram.com/sybnarynto/"
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - name: Categories
      url: /categories/
      weight: -96
    - name: Tags
      url: /tags/
      weight: -95
    - name: Search
      url: /search/
      weight: -92
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: -90
